server:
  port: 8080
spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9000/oauth2/jwks"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Unilink Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      unilink:
        gatewayserver: DEBUG