spring:
  application:
    name: "auth-server"
  datasource:
    url: jdbc:postgresql://localhost:5432/unilink_db
    username: postgres
    password: 299792
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
  config:
    import: "optional:configserver:http://localhost:8888/"
api:
  prefix: /unilink/auth

server:
  port: 9000

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/